# Generated by Django 3.1b1 on 2020-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=10)),
                ('frm', models.IntegerField(max_length=6)),
                ('to', models.IntegerField(max_length=6)),
                ('special_number', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
